config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  
 
 root 'static_pages#home'
  get '/home', to:'static_pages#home'
      get '/about', to:'static_pages#about'
      get '/services', to:'static_pages#services'
      get '/blog', to:'static_pages#blog'
      get '/contact', to:'static_pages#contact'
      
      devise_for :user
      
      resources :leads
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/lead.rb
class Lead < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
    def new
        @lead = Lead.new
    end
    
    def show
        @lead = Lead.find(params[:id])
    end
    
    def create
        @lead = Lead.new(lead_params)
        if @lead.save
       flash.notice = "Thank you! We will be in touch shortly!"
             redirect_to contact_path
           else
             render 'new'
    end

        end
    
    private
    
    def lead_params
        params.require(:lead).permit(:name,:email,:telephone, :comment)
        end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def intake
  end

  def services
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_header.html.erb
<style>
p{
font-family: 'Kaisei HarunoUmi';
}

</style>





 <nav class="navbar  navbar-fixed-top" style="border-bottom:solid;">
   
  <div class="container">
                         
       <div class="navbar-header" >
             <%= link_to image_tag("d10.png",class:"logo-d", alt: "Rails logo", width: "150"), root_path %>
            <div class = "btn-group" >
            <p class="top-logo"><b><%= link_to "DIRECT FAMILY SERVICES", root_path%><br><b style ="color:black;">747-235-0345</b></p>
           
    </div>
       <button  type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      </div>
   
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right" >
        <li ><%= link_to "ABOUT", about_path %></li>
        <li><%= link_to "SERVICES", services_path %></li>
       
        
        <li><%= link_to "CONTACT", new_lead_path %></li>
              
      
                    
              
              
              
              
              
              
              </li>
           </ul>
        </li>
     
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  
       
    <title>Direct Family Services</title>
    <meta charset="utf-8">
    <link rel="shortcut icon" href="assets/favicon.ico">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
  
       <!--------Bootstrap------>
       
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= csrf_meta_tags %>
    <%= csp_meta_tag %>



    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
        <%= javascript_importmap_tags %>
  </head>

  <body>
  <%=render 'layouts/header'%>
    <%= yield %>
  </body>
</html>

app/views/leads/new.html.erb
<style>
textarea{
width:100%;

}

.form-s{
width:19%;
}
</style>

<!-- Container (Contact Section) -->

<div id="contact" class="container-fluid bg-grey" style="margin-top:30px;border-top:none">
    <p id="contactp1" class="text-center h4" style="margin-top:20px;">Leave a quick note below and we will get back to you shortly.</p>

  <h2 class="text-center";">CONTACT</h2>
  <div class="row" style="margin-top:40px;">
    <div class="col-md-4">
      
       <p class="h4"><span class="glyphicon glyphicon-home"></span> : 10880 Wilshire Blvd</p>
        <p class="h4" style:"margin-left:30px;"> Suite 1101, Los Angeles, CA 90024</p>
            <p class="h4"><span class="glyphicon glyphicon-phone"></span> : 747-235-0345</p>
      <p class="h4"><span class="glyphicon glyphicon-envelope"></span> :  Support@DirectFamilyServices.com</p>
    </div>
   
    <div class="col-md-8 text-center"  >
    <%= form_with(model: @lead, local: true) do |f| %>
         <div class= "row" style="margin-top:10px;">
     <%= f.text_area :name ,maxlength: 255, size: "30x1" ,  placeholder:"Name" %>
    </div>
    <div class= "row" style="margin-top:10px;">
     <%= f.text_area:telephone,maxlength: 255, size: "30x1" ,  placeholder:"Telehone" %>
    </div>
        <div class= "row">
                <p align="left">Please Select your case type: </p>
  
    </div>
       
    <div class= "row" >
    
    <%= f.select :case_type, [["Divorce", "Divorce"],["Child Custody", "Child Custody"],  ["Adoption", "Adoption"], ["Visitation", "Visitiation"], ["Child Support", "Child Support"], ["Adoption", "Adoption"]],{} , { :class => 'form-control form-s'}%>
    </div>
      
    
        <div class= "row" style="margin-top:10px;">
        <%= f.text_area :comment , maxlength: 255, size: "30x5 " , placeholder:"Comment" %>
        </div>
    
        <div class= "row" style="margin-top:10px;">
        <%= f.submit "Submit", class: "btn btn-primary" %>
        </div>
</div>
  </div>
     
    <%end%>
</div>
<script>
$(window).on('resize', function() {
    if($(window).width() > 900) {
       
        $('#contactp').addClass('h3');
        $('#contactp').removeClass('h4');
       
        $('#contactp1').addClass('h3');
        $('#contactp1').removeClass('h4');
       
    
    }else{
        
        $('#contactp').removeClass('h3');
        $('#contactp').addClass('h4');
        
        $('#contactp1').removeClass('h3');
        $('#contactp1').addClass('h4');
      
    }
})



</script>

app/views/leads/show.html.erb
<h1>Leads#show</h1>
<p>Find me in app/views/leads/show.html.erb</p>

app/views/static_pages/about.html.erb
<style>

p{
font-size:20px;
color:#fff;
}


    
</style>

<body style="background-color:#9bb7d4;">
<div class = "container-fluid text-center" style="margin-top:70px;border:none">
<div style="border-bottom:solid;color:black;font-size:25px;margin-bottom:30px;">ABOUT</div>
<p>  Direct Family Services connects legal document professionals to families in need of family law support. Our legal team of document experts combine their experience along with their technical abilities to help you navigate the complex and often times bumpy road that family law may pose. Our team of engineers build and maintain our systems ensuring your documents are always on track and always moving down our document pipeline. Our team  of Case administrators/managers provide emotional well-being and support as well as answer all of your questions and concerns. </p>
</div>

 <div  class="container-fluid bg-grey">
 
  
 <div class"text-center">
<%= link_to 'Contact Us Now', new_lead_path, class: "btn btn-primary btn-lg btn-block" %>
 </div>
</div>
<body>

app/views/static_pages/contact.html.erb
<style>
span{
margin-left:20px;
color:green;

}
</style>

<div class="container-fluid" style="margin-top:100px;border-top:none;">
<h1>Thank you! Your information has been received! We will be in touch with you shortly to discuss the next steps!<span class="glyphicon glyphicon-ok"></span></h1>
        <h1>747-235-0345</h1>

         <%= link_to "Back Home", root_path, class: "btn btn-primary" %>
</div>
 
 

app/views/static_pages/home.html.erb
<script>
$(window).on('resize', function() {
    if($(window).width() > 900) {
        $('#list').addClass('h3');
        $('#list').removeClass('h4');
        $('#list1').addClass('h3');
        $('#list1').removeClass('h4');
        $('#list2').addClass('h3');
        $('#list2').removeClass('h4');
        $('#list3').addClass('h3');
        $('#list3').removeClass('h4');
        $('#list4').addClass('h3');
        $('#list4').removeClass('h4');
    }else{
        
        $('#list').removeClass('h3');
        $('#list').addClass('h4');
        $('#list1').removeClass('h3');
        $('#list1').addClass('h4');
        $('#list2').removeClass('h3');
        $('#list2').addClass('h4');
        $('#list3').removeClass('h3');
        $('#list3').addClass('h4');
        $('#list4').removeClass('h3');
        $('#list4').addClass('h4');
    }
})
</script>

<!----Hero Section--->
 <div class="container-fluid above2thou at1000" id="myPage" style="padding:0; position:relative;border-top:none;">
  <img id="my-img" src="assets/hero1.png"  alt="Nature" class="responsive a480p"/>
    <img id="my-img" src="assets/hero2.png"  alt="Nature" class="responsive b480p"/>
   <div class="top-right text-center">
       <h1 class="hero-text ">Direct Family Services</h1>
    <h1 class="hero-number ">747-235-0345</h1>
           <h1 class="hero-text" style="padding:10px;">Documents prepared for $250 Flat!</h1>
     <div class = "btn-group-vertical btn-group-nd">
              <%= link_to 'Request Assistance', new_lead_path, class: "btn btn-lg btn-primary bw" %>
    </div>
   </div>
 </div>
            
<!--------smaller screen sign in section----->
        <div class = "container">
        <p class=" text-center under-hero-font" style="color:black"><b>Documents prepared for $250 Flat!</b></p>
        <div class="container" >
     <%= link_to 'Request Assistance', new_lead_path, class: "btn btn-primary btn-lg btn-block" %>
     
    </div>
  </div>

<!-- Container (About Section) -->
<div class="container-fluid" style="padding-right:50px;padding-left:50px;">
       <p class="h2 text-center" style="border-bottom:solid;padding-bottom:50px;">Affordable Family Law help</p>
  <div class="row">
    <div class="col-xl-6 " >
     <br>
        <h2 class="h2 text-center " style="padding-bottom:20px;">How it works:</h2>
            <div>
            <ul class="list-group">
        
        <li class="list-group-item"><span id="list" class="h3"><span class="glyphicon glyphicon-pencil circle-icon "></span>We gather your information. </span></li>
           
    <li class="list-group-item"> <span id="list1" class="h3"> <span class="glyphicon glyphicon-check circle-icon"></span>We prepare your documents.  </span></li>
 
 
   <li class="list-group-item"><span id="list2" class="h3"><span class="glyphicon glyphicon glyphicon-folder-open circle-icon"></span> We help you file them. </span></li>
   
    <li class="list-group-item"><span id="list3" class="h3"><span class="glyphicon glyphicon-earphone circle-icon"></span> We stand by as your documents move through the court system.</span></li>
   
    <li class="list-group-item"> <span id="list4" class="h3"><span class="glyphicon glyphicon-hand-right circle-icon"></span> We guide you through every step of the way.</span></li>
             
             
    
  </ul>
    </div>
               
    </div>
    
    <div class="col-xl-6" >
 
       <div class="embed-responsive embed-responsive-16by9 video-top" >
   <iframe src="https://player.vimeo.com/video/602303175?h=6007183b0d" width="640" height="360" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe>
  </div>
  
  </div>
    </div>
  </div>
 <div class=" text-center " style="padding-bottom:20px;" >  <%= link_to 'Get in Touch', new_lead_path, class: "btn btn-primary btn-lg bw2" %> </div>
</div>


<!-- Container (Services) -->
<div id="portfolio" class="container-fluid text-center "style="background-color:#9bb7d4;">
  <h1>WE PREPARE DOCUMENTS FOR</h1><br>
  
  <div class="row text-center ">
      <div class="col-md-4">
      <a href=<%= new_lead_path %>> <div class="thumbnail">
    <div class="centered h2" style="top:20%">CHILD CUSTODY</div>
      <img src="assets/childcustody.png"  class="img-rounded" alt="San Francisco" width="200" height="100"  >
       </div></a>
       </div>
        
        <div class="col-md-4">
         <a href=<%= new_lead_path %>> <div class="thumbnail" >
        <div class="centered h2"style="top:7%">VISITATION</div>
      <img src="assets/visitation.png" class="img-rounded" alt="San Francisco" width="200" height="100"  >
       </div></a>
       </div>
        
        <div class="col-md-4">
         <a href=<%= new_lead_path %>> <div class="thumbnail" >
        <div class="centered h2"style="color:black;top:20%;">DIVORCE</div>
       <img src="assets/divorce.png"  class="img-rounded" alt="San Francisco" width="200" height="100"  >
       </div></a>
       </div>
    </div>
      
       <div class="row">
        <div class="col-md-4">
         <a href=<%= new_lead_path %>> <div class="thumbnail" >
        <div class="centered h2"style="left:40%">RESPONSES</div>
      <img src="assets/responses.png"  class="img-rounded" alt="San Francisco" width="200" height="100"  >
       </div></a>
       </div>
        
        <div class="col-md-4">
         <a href=<%= new_lead_path %>>  <div class="thumbnail" >
        <div class="centered h2" style="top:12%; left:47%;">CHILD SUPPORT</div>
      <img src="assets/childsupport.png" class="img-rounded" alt="San Francisco" width="200" height="100"  >
       </div></a>
       </div>
    
             <div class="col-md-4">
         <a href=<%= new_lead_path %>>  <div class="thumbnail bg-image hover-overlay ripple shadow-1-strong rounded" >
        <div class="centered h2"style="top:6%; left:40%;color:black;">ADOPTION</div>
      <img src="assets/adoption.png" class="img-rounded" alt="San Francisco" width="200" height="100"  >
       </div></a>
       </div>
  </div>
  
  </div>
  

  <div class = "container-fluid">
  <h2 class="text-center">What our customers say</h2>
  <div id="myCarousel" class="carousel slide text-center" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <h4>"Thank you Direct Family Services!"<br><span>Ricardo Rodriguez</span></h4>
      </div>
      <div class="item">
        <h4>"One word... WOW!!"<br><span>Erik Michaels</span></h4>
      </div>
      <div class="item">
        <h4>"The documents were on time and copmplete. Iam very satisfied with this service!<br><span>Adrianna Fuentes</span></h4>
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>












<!-- Container (Plans Section) -->
<div id="pricing" class="container-fluid " style="background-color:#9bb7d4;">
  <div class="text-center">
    <h1 style="margin-bottom:40px;padding-bottom:60px;">Our Services!</h1>
 </div>
  <div class="row slideanim">
  
    <div class="text-center ">
      <div class="panel panel-default text-center">
        <div class="panel-heading">
          <div class="h2" style="color:#fff;">What is included</div>
        </div>
        
                <div class="panel-body">
          <h4><strong>-  </strong>Case Manger to answer all of your questions</h4>
          <h4><strong>- </strong>Access to legal Document Professionals </h4>
          <h4><strong>- </strong>Documents Prepared</h4>
         <h4 ><strong>- </strong>Documents filed</h4>
          </div>
        <div class="panel-footer">
            <%= link_to 'Learn More', new_lead_path, class: "btn btn-lg" %>
        </div>
        
      </div>
    </div>
    
    </div>
  </div>
</div>


<!-- Container (Contact Section) -->
<div id="contact" class="container-fluid bg-grey">
  <h2 class="text-center">CONTACT</h2>
  
 <div class"text-center">
<%= link_to 'Contact Us Now', new_lead_path, class: "btn btn-primary btn-lg btn-block" %>
 </div>
</div>


<!-- Image of location/map -->


<div class="container-fluid" style="padding:0px;position:relative">
  <img src="assets/footer.png" class="hide-footer1" alt="Snow" style="width:100%;">
    <img src="assets/footer2.png" class="hide-footer2" alt="Snow" style="width:100%;">
  <div class="footer-pic h4 container-fluid" style="background-color:white">
   10880 Wilshire Blvd<br> Suite 1101,<br> Los Angeles, CA 90024 <br>747-235-0345
 </div>
 
</div>


<footer class="container-fluid text-center" style="padding:0;">
  <a href="#myPage" title="To Top">
    <span class="glyphicon glyphicon-chevron-up"></span>
    <p>top of page</p>
  </a>
  <p>Direct Family Services all rights reserved 2021</p>
  
   
</footer>

<script>
$(document).ready(function(){
  // Add smooth scrolling to all links in navbar + footer link
  $(".navbar a, footer a[href='#myPage']").on('click', function(event) {
    // Make sure this.hash has a value before overriding default behavior
    if (this.hash !== "") {
      // Prevent default anchor click behavior
      event.preventDefault();

      // Store hash
      var hash = this.hash;

      // Using jQuery's animate() method to add smooth page scroll
      // The optional number (900) specifies the number of milliseconds it takes to scroll to the specified area
      $('html, body').animate({
        scrollTop: $(hash).offset().top
      }, 900, function(){
   
        // Add hash (#) to URL when done scrolling (default click behavior)
        window.location.hash = hash;
      });
    } // End if
  });
  
  $(window).scroll(function() {
    $(".slideanim").each(function(){
      var pos = $(this).offset().top;

      var winTop = $(window).scrollTop();
        if (pos < winTop + 600) {
          $(this).addClass("slide");
        }
    });
  });
})

$(document).on('click','.navbar-collapse.in',function(e) {
    if( $(e.target).is('a:not(".dropdown-toggle")') ) {
        $(this).collapse('hide');
    }
});
</script>

app/views/static_pages/intake.html.erb
<h1>StaticPages#intake</h1>
<p>Find me in app/views/static_pages/intake.html.erb</p>

app/views/static_pages/services.html.erb
<!-- Container (Services) -->
<div id="portfolio" class="container-fluid text-center "style="background-color:#9bb7d4;margin-top:50px;border-bottom:solid;">
  <h1>WE PREPARE DOCUMENTS FOR</h1><br>
  
  <div class="row text-center ">
      <div class="col-md-4">
      <a href=<%= new_lead_path %>> <div class="thumbnail">
      <h1 class="centered" style="top:20%">CHILD CUSTODY</h1>
      <img src="assets/childcustody.png"  class="img-rounded" alt="San Francisco" width="200" height="100"  >
       </div></a>
       </div>
        
        <div class="col-md-4">
         <a href=<%= new_lead_path %>> <div class="thumbnail" >
        <h1 class="centered" style="top:12%">VISITATION</h1>
      <img src="assets/visitation.png" class="img-rounded" alt="San Francisco" width="200" height="100"  >
       </div></a>
       </div>
        
        <div class="col-md-4">
         <a href=<%= new_lead_path %>> <div class="thumbnail" >
        <h1 class="centered" style="color:black;top:20%;">DIVORCE</h1>
       <img src="assets/divorce.png"  class="img-rounded" alt="San Francisco" width="200" height="100"  >
       </div></a>
       </div>
    </div>
      
       <div class="row">
        <div class="col-md-4">
         <a href=<%= new_lead_path %>> <div class="thumbnail" >
        <h1 class="centered"style="left:40%">RESPONSES</h1>
      <img src="assets/responses.png"  class="img-rounded" alt="San Francisco" width="200" height="100"  >
       </div></a>
       </div>
        
        <div class="col-md-4">
         <a href=<%= new_lead_path %>>  <div class="thumbnail" >
        <h1 class="centered" style="top:12%; left:47%;">CHILD SUPPORT</h1>
      <img src="assets/childsupport.png" class="img-rounded" alt="San Francisco" width="200" height="100"  >
       </div></a>
       </div>
    
             <div class="col-md-4">
         <a href=<%= new_lead_path %>>  <div class="thumbnail bg-image hover-overlay ripple shadow-1-strong rounded" >
        <h1 class="centered" style="top:8%; left:40%;color:black;">ADOPTION</h1>
      <img src="assets/adoption.png" class="img-rounded" alt="San Francisco" width="200" height="100"  >
       </div></a>
       </div>
  </div>
  
  </div>
  



</div>
 <div  class="container-fluid bg-grey">
 
  
 <div class"text-center">
<%= link_to 'Contact Us Now', new_lead_path, class: "btn btn-primary btn-lg btn-block" %>
 </div>
</div>